var test = require('tape', valid);
var addressit = require('..');

function valid(t) {
  var input = '15 FOO ' + t.name + ' BARVILLE';
  var address;

  t.plan(3);
  address = addressit(input);

  t.equal(address.number, '15');
  t.equal(address.street, 'FOO ' + t.name.toUpperCase());
  t.deepEqual(address.regions, ['BARVILLE']);
}

test('ALLEY', valid);
test('ALLY', valid);
test('APPROACH', valid);
test('APP', valid);
test('ARCADE', valid);
test('ARC', valid);
test('AVENUE', valid);
test('AV', valid);
test('AVE', valid);
test('BOULEVARD', valid);
test('BLVD', valid);
test('BROW', valid);
test('BYPASS', valid);
test('BYPA', valid);
test('CAUSEWAY', valid);
test('CWAY', valid);
test('CIRCUIT', valid);
test('CCT', valid);
test('CIRCUS', valid);
test('CIRC', valid);
test('CLOSE', valid);
test('CL', valid);
test('COPSE', valid);
test('CPSE', valid);
test('CORNER', valid);
test('CNR', valid);
// test('COVE', valid);
test('COURT', valid);
test('CT', valid);
test('CRT', valid);
test('CRESCENT', valid);
test('CRES', valid);
test('DRIVE', valid);
test('DR', valid);
// test('END', valid);
test('ESPLANANDE', valid);
test('ESP', valid);
// test('FLAT', valid);
test('FREEWAY', valid);
test('FWAY', valid);
test('FRONTAGE', valid);
test('FRNT', valid);
// test('GARDENS', valid);
// test('GDNS', valid);
test('GLADE', valid);
test('GLD', valid);
// test('GLEN', valid);
test('GREEN', valid);
test('GRN', valid);
// test('GROVE', valid);
// test('GR', valid);
// test('HEIGHTS', valid);
// test('HTS', valid);
test('HIGHWAY', valid);
test('HWY', valid);
test('LANE', valid);
test('LN', valid);
test('LINK', valid);
test('LOOP', valid);
test('MALL', valid);
test('MEWS', valid);
test('PACKET', valid);
test('PCKT', valid);
test('PARADE', valid);
test('PDE', valid);
// test('PARK', valid);
test('PARKWAY', valid);
test('PKWY', valid);
test('PLACE', valid);
test('PL', valid);
test('PROMENADE', valid);
test('PROM', valid);
test('RESERVE', valid);
test('RES', valid);
// test('RIDGE', valid);
// test('RDGE', valid);
test('RISE', valid);
test('ROAD', valid);
test('RD', valid);
test('ROW', valid);
test('SQUARE', valid);
test('SQ', valid);
test('STREET', valid);
test('ST', valid);
test('STRIP', valid);
test('STRP', valid);
test('TARN', valid);
test('TERRACE', valid);
test('TCE', valid);
test('THOROUGHFARE', valid);
test('TFRE', valid);
test('TRACK', valid);
test('TRAC', valid);
test('TRAIL', valid);
test('TRL', valid);
test('TRUNKWAY', valid);
test('TWAY', valid);
// test('VIEW', valid);
test('VISTA', valid);
test('VSTA', valid);
test('WALK', valid);
test('WAY', valid);
test('WALKWAY', valid);
test('WWAY', valid);
test('YARD', valid);
