// @flow

/* ::
import type { Street } from './flow-types';
*/

const STREET_ALIASES /*: Map<Street, Array<string>> */= new Map([
  ['ALLEY', ['ALLY']],
  ['APPROACH', ['APP']],
  ['ARCADE', ['ARC']],
  ['AVENUE', ['AV', 'AVE']],
  ['BOULEVARD', ['BLVD']],
  ['BROW', []],
  ['BYPASS', ['BYPA']],
  ['CAUSEWAY', ['CWAY']],
  ['CIRCUIT', ['CCT']],
  ['CIRCUS', ['CIRC']],
  ['CLOSE', ['CL']],
  ['COPSE', ['CPSE']],
  ['CORNER', ['CNR']],
  // ['COVE', []],
  ['COURT', ['CT', 'CRT']],
  ['CRESCENT', ['CRES']],
  ['DRIVE', ['DR']],
  // ['END', []],
  ['ESPLANADE', ['ESP']],
  // ['FLAT', []],
  ['FREEWAY', ['FWAY']],
  ['FRONTAGE', ['FRNT']],
  // ['GARDENS', ['GDNS']],
  ['GLADE', ['GLD']],
  // ['GLEN', []],
  ['GREEN', ['GRN']],
  // ['GROVE', ['GR']],
  // ['HEIGHTS', ['HTS']],
  ['HIGHWAY', ['HWY']],
  ['LANE', ['LN']],
  ['LINK', []],
  ['LOOP', []],
  ['MALL', []],
  ['MEWS', []],
  ['PACKET', ['PCKT']],
  ['PARADE', ['PDE']],
  // ['PARK', []],
  ['PARKWAY', ['PKWY']],
  ['PLACE', ['PL']],
  ['PROMENADE', ['PROM']],
  ['RESERVE', ['RES']],
  // ['RIDGE', ['RDGE']],
  ['RISE', []],
  ['ROAD', ['RD']],
  ['ROW', []],
  ['SQUARE', ['SQ']],
  ['STREET', ['ST']],
  ['STRIP', ['STRP']],
  ['TARN', []],
  ['TERRACE', ['TCE']],
  ['THOROUGHFARE', ['TFRE']],
  ['TRACK', ['TRAC']],
  ['TRAIL', ['TRL']],
  ['TRUNKWAY', ['TWAY']],
  // ['VIEW', []],
  ['VISTA', ['VSTA']],
  ['WALK', []],
  ['WAY', ['WY']],
  ['WALKWAY', ['WWAY']],
  ['YARD', []]
]);
  
exports.getStreet = () => {

};
